config/routes.rb
GenericPeopleRails::Engine.routes.draw do
  match "generic_people_rails/forgot_password" => "credentials#forgot_password" , as: :forgot_password, via: [:get , :post]
  match "generic_people_rails/reset_password" => "credentials#reset_password" , as: :reset_password, via: [:get , :post]  
  match "generic_people_rails/resend_confirmation" => "credentials#resend_confirmation" , as: :resend_confirmation, via: [:get, :post]   
  match "generic_people_rails/confirm_account" => "credentials#confirm_account" , as: :confirm_account, via: :get
end

Rails.application.routes.draw do
  match "forgot_password" => "generic_people_rails/credentials#forgot_password" , as: :forgot_password, via: [:get , :post]
  match "reset_password" => "generic_people_rails/credentials#reset_password" , as: :reset_password, via: [:get , :post]
  match "resend_confirmation" => "generic_people_rails/credentials#resend_confirmation" , as: :resend_confirmation, via: [:get, :post]  
  match "confirm_account" => "generic_people_rails/credentials#confirm_account" , as: :confirm_account, via: :get   
end

app/models/credential.rb
require 'bcrypt'
class Credential < ActiveRecord::Base
  include BCrypt
    
  belongs_to :member, optional: true
  has_many :api_tokens, dependent: :destroy

  belongs_to :email, optional: true
  accepts_nested_attributes_for :email

  has_many :permissions, dependent: :destroy
  accepts_nested_attributes_for :permissions
  
  def password
    if @password
      @password
    else
      if salt
        Password.new(salt)
      else 
        nil #hmmm happens with fb login...
      end
    end
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.salt = @password
  end

  def self.authenticate(address, password)
    authenticated = nil

    if address.present?
      emails = Email.where(address: address)
      emails.each do |email|
        creds = self.where(email: email)

        # If there are multiple credentials, see if any of them are the right one.
        creds.each do |cred|
          if cred.password == password
            authenticated = cred
            
            # this is here because if someone signs up, then connects the same
            # email using facebook, they have to use their original password
            # to connect and now we need to link their other creds to the right member
            # account.
            cred.email.credentials.update_all(member_id: cred.member.id)
            break
          end
        end
        break if authenticated
      end
    end
    if authenticated
      authenticated.member.update_last_login
    end
    authenticated
  end

  # Need to allow to return error messages
  # So returns array
  # [object, errors]  
  
  def self.sign_up(address, password, hash = {})
    cred = nil
    person = nil
    member = nil
    email = Email.find_by(address: address)
    email ||= Email.new(address: address)
    return [nil, email.errors.full_messages.to_sentence] if !email.valid?

    send_mail = (hash[:send_mail].present? && hash[:send_mail] == "true") ? true : false

    # Validate person details, strong params.
    if hash.respond_to?(:permit)
      person_params = hash.permit(:name, :birthdate, :fname, :lname, :minitial)
    else
      person_params = hash.slice(:name, :birthdate, :fname, :lname, :minitial)
    end
    person = email.person rescue nil
    person ||= Person.new(person_params)
    return [nil, person.errors.full_messages.to_sentence] if !person.valid?

    # Make all creations atomic where possible.
    Member.transaction do
      # Check to see if this email is already in use.
      e = email if email.id
      member = e.member if e

      # If in use, and there are any credential records, try to authenticate.
      if e and  self.find_by(email: e)
        msg = nil
        cred = self.authenticate(address, password)

        if not cred
          # Try hard to understand what's happening.  If the user has signed up via linkedIn or Facebook,
          # and then is re-signing up, let's tell them to login using those services.
          creds = self.where(email: e)
          has_pass = nil
          providers = []
          creds.each do |c|
            if c.password or (c.respond_to?(:salt) and c.salt)
              has_pass = c
              break
            else 
              providers.push c.provider if c.provider
            end
          end

          msg = "Password doesn't match existing user" if has_pass
          msg = "You've never used a password - login with " + providers.to_sentence(two_words_connector: ' or ', last_word_connector: ', or ') if not providers.empty?
          return [cred, msg]
        end
      end
      email.save if not email.id
      person.emails << email if not person.emails.include?(email)
      person.save
      member = Member.create(person_id: person.id, status: GenericPeopleRails::Config.default_member_status) if not member
    end
        
    cred ||= self.create(email: email, password: password, member: member, uid: SecureRandom.uuid) if member and member.id
    (cred.send_welcome rescue nil) if cred && send_mail
    [cred, cred ? cred.errors.full_messages.to_sentence : nil]
  end

  # User in the hash is already externally authenticated by facebook, google+, etc.
  # Credential.authenticate_oauth finds or creates a credential that matches
  # the oauth token of the authenticated user.  If a user has authenticated once with
  # facebook, and then they want to authenticate with google+, we allow that.
  # Need to allow to return error messages
  # So returns array
  # [object, errors]
  def self.authenticate_oauth(hash)
    return [nil, "incorrect credentials: :hash[:uid] not set"] if hash[:uid].blank?
    return [nil, "incorrect credentials: :hash[:provider] is not set"] if hash[:provider].blank?
    
    send_mail = (hash[:send_mail].present? && hash[:send_mail] == "true") ? true : false
    
    Member.transaction do
      email = Email.find_or_create_by(address: hash[:email]) # email required
      cred = self.find_or_create_by(uid: hash[:uid], provider: hash[:provider], email: email)
      
      # We have a credential, either new, or old.  If we have an email, set the email
      # in the credential.
      #cred.email = email if email
      # Make up a password: but only if there isn't already one there!
      cred.password ||= SecureRandom.hex(30)
      cred.save
    
      #check to see if member account exists for this email
      if not cred.member
        email.credentials.each do |other_crd|
          if other_crd != cred
            if !other_crd.member.nil?
              #return [nil, "An account already exists with this email address."]
              cred.update_attribute(:member_id, other_crd.member_id)
              break
            end
          end
        end
        if !cred.member 
          # if still here, ok to create- only gets name from weblogin 
          person_hash = {person: {name: hash[:name]}}
          person = Person.create(person_hash[:person].slice(:name))
          person.emails << email if email

          member = Member.create(person: person, status: GenericPeopleRails::Config.active_status)
          cred.member = member
          cred.save
          cred.send_welcome if send_mail
        end
      end

      [cred]
    end
  end

  def can(name)
    self.permissions.where(permission_label: PermissionLabel.get(name)).first
  end

  def allow_to(name)
    self.permissions.find_or_create_by_permission_label_id(PermissionLabel.get(name).id)
  end
  
  def to_s
    "#<Credential: #{self.id}: #{self.email.address}>"
  end

  def as_json(options={})
    super(:only => [:id, :member_id, :created_at])
  end
  
  def send_welcome
    if self.member.credentials.length == 1 && defined?(ActionMailer) && GenericPeopleRails::Config.send_welcome 
      GprMailer.welcome(self.member, self).deliver  
    end
  end
   
end

app/controllers/generic_people_rails/application_controller.rb
module GenericPeopleRails
  class ApplicationController < ActionController::Base

  end
end

app/controllers/generic_people_rails/credentials_controller.rb
module GenericPeopleRails
  class CredentialsController < ApplicationController
    layout GenericPeopleRails::Config.layout
    before_action :check_logged_in, only: [:resend_confirmation, :forgot_password, :reset_password]
    
    # for changing password
    def resend_confirmation
      @params = params
      email = @params[:email]
      if email.present?
        get_valid_cred(email)
        if @cred
          @cred.update(uid: SecureRandom.uuid)
          GprMailer.resend_confirmation(@cred.member, @cred).deliver if defined?(ActionMailer)     
          flash.now[:notice] = "Your confirmation email has been resent." 
        end
      end
    end
    
    def confirm_account
      email = params[:email]
      token = params[:token]     
      uid = params[:uid]
      if email.present? && token.present?
        useremail = Email.where(address: email).first
        cred = Credential.find_by(email_id: useremail.id, uid: token) if useremail
        if useremail && cred
          @member = cred.member
          if @member.id == uid.to_i
            @member.update(status: 'confirmed')
            useremail.update(confirmed: true)
            GprMailer.confirmed(@member).deliver        
            flash.now[:notice] = "Thank you, your account has been confirmed!"
          else
            flash.now[:alert] = "Valid account not found"
          end
        else
          flash.now[:alert] = "Valid account not found"
        end
      else
        flash.now[:alert] = "Valid account not found"
      end
      redirect_to main_app.root_url
    end    
  
    def forgot_password
      @params = params
      email = @params[:email]
      
      if email.present?
        get_valid_cred(email)
        if @cred
          #if cred.member.deleted_at.nil?
            @cred.update(uid: SecureRandom.uuid)
            GprMailer.reset_password(@cred.member, @cred).deliver if defined?(ActionMailer)        
            flash.now[:notice] = "An email has been sent to you with instructions on resetting your password."
          #else
            #flash.now[:error] = "Your account has been cancelled. Please contact an administrator"
          #end
        else
          flash.now[:error] = "Valid account not found"
        end
      end
    end
    
    def reset_password
      @params = params
      @success = false
      
      #check for credentials in forgot password email
      @member = Member.find(params[:uid])
      @cred = @member.credentials.find_by(uid: params[:token]) if @member
      if !(@member && @cred)
        #not the right guy
        flash.now[:alert] = "Invalid User Account."
      else
        #form submit - process
        if params[:password] && params[:password_confirm] 
          id_mem = Member.find(params[:id])
          if id_mem != @member
            flash.now[:alert] = "Invalid User Account."
          else
            if params[:password] == params[:password_confirm]
              # set creds all with same password, make sure member field is populated (side effect of oauth).
              @cred.email.credentials.each do |c|
                c.member_id = @member.id
                c.password = params[:password]
                c.save
              end
              #@cred.update(password: params[:password])
              GprMailer.password_was_reset(@member, @cred).deliver if defined?(ActionMailer)        
              flash.now[:notice] = "Congratulations You reset your password."
              @success = true
            else
              flash.now[:alert] = "Your passwords do not match!"
            end
          end
        end
      end
      if @success
        redirect_to "/"
      end
    end
    
    private
      def check_logged_in
        if authenticated? 
          redirect_to main_app.root_url
        end
      end
      
      def get_valid_cred(email)
        @email = Email.where(address: email).first
        if @email
          creds = Credential.where(email_id: @email.id)
          if creds.empty?
            @msg = "Valid account not found."
          else
            @cred = creds.first
            if GenericPeopleRails::Config.acts_paranoid && @cred.member.is_cancelled?
              @msg = "Your account has been closed. Please contact the site's administrator"
              @cred = nil
            end
          end
        else  
          @msg = "Valid account not found."
        end
      end
  end
end

app/views/generic_people_rails/credentials/forgot_password.html.erb
<div class="gpr-container">
  <div class="forgot-password-form">
    
    <p>Enter your email and we will send you instructions on resetting your password.</p>
  
    <%= form_tag forgot_password_path do -%>
          
      <div class="control-group">
        <div class="input-group input-group-grey">
          <%= email_field_tag 'email', ((@params) ? @params[:email] : "" ), class: 'form-control', required: 'required', :placeholder => "Email" %>
          <span class="input-group-addon">
            <%= image_tag("dark-email.png", :alt => 'lock') %>
          </span>
        </div>
      </div>
      <div>
        <%= submit_tag 'Send', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/generic_people_rails/credentials/resend_confirmation.html.erb
<div class="gpr-container">
  <div class="forgot-password-form">
    
    <p>Enter your email and we will resend your confirmation email.</p>
  
    <%= form_tag resend_confirmation_path do -%>
          
      <div class="control-group">
        <div class="input-group input-group-grey">
          <%= email_field_tag 'email', ((@params) ? @params[:email] : "" ), class: 'form-control', required: 'required', :placeholder => "Email" %>
          <span class="input-group-addon">
            <%= image_tag("dark-email.png", :alt => 'lock') %>
          </span>
        </div>
      </div>
      <div>
        <%= submit_tag 'Send', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/generic_people_rails/credentials/reset_password.html.erb
<% if @member && @cred %>
  <div class="gpr-container">
    <%= form_tag reset_password_path do -%>
      <%= hidden_field_tag :id, @member.id %>
      <%= hidden_field_tag :uid, @params[:uid]  %>
      <%= hidden_field_tag :token, @params[:token] %>
      <h6>New Password</h6>
      <div class="form-group">
        <div class="input-group full-width">
          <%= password_field_tag "password", '', required: 'required', class: 'form-control md5-input', :placeholder => "New Password" %>
          <div class="form-control-feedback fix-field-icon not-focus">
            <%= image_tag "light-password-lock.png" %>
          </div>
          <div class="form-control-feedback fix-field-icon focus">
            <%= image_tag "dark-password-lock.png" %>
          </div>
        </div>
      </div>
      <h6>Retype New Password</h6>
      <div class="form-group">
        <div class="input-group full-width">
          <%= password_field_tag "password_confirm", '', class: 'form-control md5-input', equalto: "#password", :placeholder => "Confirm Password" %>
          <div class="form-control-feedback fix-field-icon not-focus">
            <%= image_tag "light-password-lock.png" %>
          </div>
          <div class="form-control-feedback fix-field-icon focus">
            <%= image_tag "dark-password-lock.png" %>
          </div>
        </div>
      </div>
      <div class="actions settings-submit-button">
        <%= submit_tag 'Update', :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
<% end %>